#!/usr/bin/env node

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')

const root = path.resolve(__dirname, '..')
const source = file => fs.readFileSync(path.join(root, file), 'utf8')

const context = { window: {} }
vm.createContext(context)
vm.runInContext(source('js/data/monsters.js'), context)

const bandit = context.window.MONSTERS.find(monster => monster.id === 'p_bandit_leader')
assert.ok(bandit, 'bandit leader must exist')
assert.equal(bandit.maxHp, 9)
assert.equal(bandit.props.banditCrew.length, 2)
assert.equal(bandit.abilities.charge.every, 4)
assert.equal(bandit.abilities.charge.interruptDamage, 3)
assert.equal(bandit.props.chargedAttack.keepChargeName, true)
assert.equal(bandit.props.chargedAttack.taskSeconds, 40)

const attacks = new Map(bandit.attacks.map(attack => [attack.roll, attack]))
assert.equal(attacks.get(1).part, 'oral')
assert.equal(attacks.get(1).actor, '桥洞哨探')
assert.equal(attacks.get(2).special, 'steal')
assert.equal(attacks.get(2).gold, 12)
assert.ok(attacks.get(2).repeat)
assert.equal(attacks.get(2).taskSequence.length, 2)
assert.equal(attacks.get(3).requiresCrew, 'bandit-lookout')
assert.equal(attacks.get(3).secondaryPart, 'oral')
assert.equal(attacks.get(3).genderedPart, true)
assert.deepEqual(Array.from(attacks.get(4).taskSequence, step => step.count), [15, 5])
assert.equal(attacks.get(5).requiresCrew, 'bandit-lookout')
assert.equal(attacks.get(5).part, 'oral')
assert.equal(attacks.get(5).special, 'choke')
assert.equal(attacks.get(5).solo.special, 'choke')
assert.equal(attacks.get(6).special, 'bandit_rotate')
assert.ok(attacks.get(6).rotate[3])
assert.ok(attacks.get(6).rotate[2])
assert.ok(attacks.get(6).rotate[1])
assert.equal(attacks.get(6).rotate[3].taskSeconds, 45)
assert.equal(attacks.get(6).rotate[2].taskSeconds, 30)
assert.match(attacks.get(6).rotate[3].desc, /每人/)

const battle = source('js/ui/battle.js')
assert.match(battle, /banditAmbushPending/, 'opening ambush must wait for the lookout')
assert.match(battle, /banditAmbushStrike/, 'lookout ambush must reuse the enemy-turn resolver')
assert.match(battle, /attack\.rotate\[Math\.max\(1, Math\.min\(3, living\)\)\]/, 'rotation must scale with living bandits')
assert.match(battle, /attack\.part \|\| chRes\.part/, 'explicit attack parts must win over prose parsing')
assert.match(battle, /attack\.taskSequence/, 'multi-part actions must share one final damage settlement')
assert.match(battle, /effAttack\.secondaryPart === 'oral'/, 'dual-part attacks must honor gag equipment')

const battleSystem = source('js/systems/battle.js')
assert.match(battleSystem, /banditAmbushPending/, 'battle state must remember the opening ambush')
assert.match(battleSystem, /banditCoverUsed/, 'each crew member must intercept at most one leader hit')
assert.match(battleSystem, /banditClothesTaken/, 'battle result must remember clothes taken by the cutpurse')
assert.match(battleSystem, /banditNoCover/, 'returning challengers must disable crew interception')
assert.match(battleSystem, /banditGoldStolen/, 'defeat settlement must remember gold already stolen in battle')

const abilities = source('js/systems/enemy-abilities.js')
assert.match(abilities, /keepChargeName/, 'signature executions must keep their own names')

const commission = source('js/systems/commission.js')
assert.match(commission, /哨探会先从阴影里按住你/, 'hideout briefing must mention the lookout ambush')
assert.match(commission, /烂母畜操完扔出去/, 'defeat must treat the player as discarded loot')
assert.match(commission, /defeat-verify/, 'first defeat aftermath must be resumable')
assert.match(commission, /_pBanditClothesLocked/, 'defeat must lock original clothes in the leader chest')
assert.match(commission, /跪上货箱换人/, 'returning players must be able to trade submission for the witness')
assert.match(commission, /victory-fall/, 'bandit victory aftermath must resume before witness rescue')
assert.match(commission, /踩住他，逼问雇主/, 'victory must let the player decide the leader fate')
assert.match(commission, /腿上的弃畜号/, 'revenge victory must resolve the defeat mark')
assert.match(commission, /破损原衣披在肩上/, 'recovered clothes must not be equipped automatically')

console.log('bandit hideout tests passed')
