#!/usr/bin/env node

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')

const root = path.resolve(__dirname, '..')
const source = file => fs.readFileSync(path.join(root, file), 'utf8')

const context = { window: {} }
vm.createContext(context)
vm.runInContext(source('js/data/monsters.js'), context)
vm.runInContext(source('js/data/monsters/bandit-leader.js'), context)

const bandit = context.window.MONSTER_DEFINITIONS.find(monster => monster.id === 'p_bandit_leader')
assert.ok(bandit, 'bandit leader must exist')
assert.equal(bandit.maxHp, 9)
assert.equal(bandit.props.banditCrew.length, 2)
assert.equal(bandit.abilities.charge.every, 4)
assert.equal(bandit.abilities.charge.interruptDamage, 3)
assert.equal(bandit.props.chargedAttack.keepChargeName, true)
assert.equal(bandit.props.chargedAttack.taskSeconds, 40)

const attacks = new Map(bandit.attacks.map(attack => [attack.roll, attack]))
assert.equal(attacks.get(1).part, 'oral')
assert.equal(attacks.get(1).actor, '桥洞哨探')
assert.equal(attacks.get(2).special, 'steal')
assert.equal(attacks.get(2).gold, 12)
assert.ok(attacks.get(2).repeat)
assert.equal(attacks.get(2).taskSequence.length, 2)
assert.deepEqual(Array.from(attacks.get(3).requiresAllCrew), ['bandit-lookout', 'bandit-cutpurse'])
assert.equal(attacks.get(3).secondaryPart, 'oral')
assert.equal(attacks.get(3).genderedPart, true)
assert.deepEqual(Array.from(attacks.get(4).taskSequence, step => step.count), [15, 5])
assert.equal(attacks.get(5).requiresCrew, 'bandit-lookout')
assert.equal(attacks.get(5).part, 'oral')
assert.equal(attacks.get(5).special, 'choke')
assert.equal(attacks.get(5).solo.special, 'choke')
assert.equal(attacks.get(6).special, 'bandit_rotate')
assert.ok(attacks.get(6).rotate[3])
assert.ok(attacks.get(6).rotate[2])
assert.ok(attacks.get(6).rotate[1])
assert.equal(attacks.get(6).rotate[3].taskSeconds, 45)
assert.equal(attacks.get(6).rotate[2].taskSeconds, 30)
assert.match(attacks.get(6).rotate[3].desc, /每人/)

const battle = source('js/ui/battle.js')
assert.match(battle, /banditAmbushPending/, 'opening ambush must wait for the lookout')
assert.match(battle, /banditAmbushStrike/, 'lookout ambush must reuse the enemy-turn resolver')
assert.match(battle, /attack\.rotate\[Math\.max\(1, Math\.min\(3, living\)\)\]/, 'rotation must scale with living bandits')
assert.match(battle, /attack\.part \|\| chRes\.part/, 'explicit attack parts must win over prose parsing')
assert.match(battle, /attack\.taskSequence/, 'multi-part actions must share one final damage settlement')
assert.match(battle, /effAttack\.secondaryPart === 'oral'/, 'dual-part attacks must honor gag equipment')

const battleSystem = source('js/systems/battle.js')
assert.match(battleSystem, /banditAmbushPending/, 'battle state must remember the opening ambush')
assert.match(battleSystem, /banditCoverUsed/, 'each crew member must intercept at most one leader hit')
assert.match(battleSystem, /banditClothesTaken/, 'battle result must remember clothes taken by the cutpurse')
assert.match(battleSystem, /banditNoCover/, 'returning challengers must disable crew interception')
assert.match(battleSystem, /banditGoldStolen/, 'defeat settlement must remember gold already stolen in battle')

const abilities = source('js/systems/enemy-abilities.js')
assert.match(abilities, /keepChargeName/, 'signature executions must keep their own names')

const commission = source('js/systems/prologue-wilderness.js')
assert.match(commission, /哨探已经从斜坡阴影里摸到你背后/, 'hideout briefing must mention the lookout ambush')
assert.match(commission, /送上门的飞机杯/, 'first defeat must keep the player as a toy for days')
assert.match(commission, /defeat-toy/, 'toy session must be resumable')
assert.match(commission, /witness-trade/, 'empty-handed witness trade must be resumable')
assert.match(commission, /_pBanditTradeStep = step \+ 1/, 'empty-handed witness trade must save every completed step')
assert.match(commission, /这不是上次那只肉便器吗/, 'returning players must be recognized')
assert.match(commission, /欠 1200G 把人带走/, 'ransom debt must remain available')
assert.match(commission, /victory-fall/, 'bandit victory aftermath must resume before witness rescue')
assert.match(commission, /战胜强盗头目/, 'victory should not keep the discarded-toy framing')
assert.match(commission, /先不穿/, 'victory clothes can be left unequipped')
assert.match(commission, /collectBanditBridgeToll/, 'unpaid ransom must tax later bridge visits')

console.log('bandit hideout tests passed')
