#!/usr/bin/env node

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const context = { window: {}, State: { get: () => ({ gender: 'female' }) } }
vm.createContext(context)
vm.runInContext(read('js/data/monsters.js'), context)
vm.runInContext(read('js/data/monsters/bandit-leader.js'), context)

const boss = context.window.MONSTER_DEFINITIONS.find(monster => monster.id === 'p_bandit_leader')
assert.ok(boss)
assert.equal(boss.maxHp, 9)
assert.deepEqual(Array.from(boss.props.banditCrew, member => member.hp), [3, 3])
assert.equal(boss.abilities.charge.interruptDamage, 3)
assert.deepEqual(Array.from(boss.attacks.find(attack => attack.roll === 3).requiresAllCrew), ['bandit-lookout', 'bandit-cutpurse'])
assert.equal(boss.props.banditSummonEvery, 3)
assert.equal(boss.attacks.find(attack => attack.roll === 3).secondaryPart, 'oral')
assert.deepEqual(Array.from(boss.attacks.find(attack => attack.roll === 4).taskSequence, step => step.count), [15, 5])
assert.ok(boss.attacks.find(attack => attack.roll === 2).repeat)
const leaderOnlyUses = context.window.BanditLeaderContent.pickDefeatToyUses(3, [])
assert.ok(leaderOnlyUses.every(use => use.actor.includes('头目')), 'defeated crew must not reappear in defeat tasks')

const battle = read('js/systems/battle.js')
assert.match(battle, /banditCoverUsed/)
assert.match(battle, /banditClothesTaken/)
assert.match(battle, /banditLivingCrewIds/)
const ui = read('js/ui/battle.js')
assert.match(ui, /p_bandit_cutpurse/)
const abilities = read('js/systems/enemy-abilities.js')
assert.match(abilities, /banditSummonEvery/)
assert.match(abilities, /es\.charging && hitMain/)
const story = read('js/systems/prologue-wilderness.js')
assert.match(story, /function recoverBanditClothes/)
assert.match(story, /playBanditToyDefeat/)

console.log('bandit leader tests passed')
